

PEERNAME = 'NAME'  # request a peer's canonical id
LISTPEERS = 'LIST'
INSERTPEER = 'JOIN'
PEERQUIT = 'QUIT'
REPLY = "REPL"
ERROR = "ERRO"

BLOCK_GET = 'BGET'
MAX_BLOCK_HEIGHT = 'BHGT'
BLOCK_HEIGHT = 'BBHT'
RELAY_TRANSACTION = 'RETX'
RELAY_BLOCK = 'REBK'
